### ISSUE TITLE
[Metaissue] Memory allocators in Gramine, their performance and possible alternatives

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gramine#1767]
### Description of the feature

Memory allocators in Gramine were written ~15 years ago. It's time to re-evaluate them and propose alternatives.

I want to start a discussion on this topic. In particular, the next posts will contain information on:
- [ ] Description of current memory allocators:
   - [ ] MEMMGR fixed-size allocator: for specific objects in specific subsystems (currently only in LibOS)
   - [ ] SLAB variable-size allocator: generic backend for `malloc` and `free` in all other subsystems (both in LibOS and in PAL)
- [ ] Users of current memory allocators:
   - [ ] Users of MEMMGR
   - [ ] Users of SLAB
- [ ] Statistics using a set of common workloads:
   - [ ] Stats for MEMMGR
   - [ ] Stats for SLAB
- [ ] Discussion on the need of **two separate** allocators
- [ ] Conclusions: Open issues, unimplemented functionality, perf bottlenecks
- [ ] Bonus: need for [object caching](https://people.eecs.berkeley.edu/~kubitron/courses/cs194-24-S13/hand-outs/bonwick_slab.pdf)? (i.e., keeping objects not just pre-allocated but also in *initialized* state)
- [ ] Possible alternatives

### Why Gramine should implement it?

We see more and more performance bottlenecks in memory/object allocation inside Gramine itself. They all stem from the fact that our memory allocators are old, ad-hoc, not scalable, and not CPU- and cache-friendly; also our allocators do not perform *object caching*.

Just a couple of recent examples:
- https://github.com/gramineproject/gramine/pull/1763
- https://github.com/gramineproject/gramine/pull/1723
- https://github.com/gramineproject/gramine/pull/1615
- https://github.com/gramineproject/gramine/blob/e740728548ef52615cffdb64f573a998abdfa61f/libos/src/sys/libos_sched.c#L177-L189?plain=1
- https://github.com/gramineproject/gramine/blob/e740728548ef52615cffdb64f573a998abdfa61f/libos/src/sys/libos_poll.c#L60-L76?plain=1

For possible alternatives (in Rust), see this comment: https://github.com/gramineproject/gramine/pull/1723#pullrequestreview-1864216238

**Comment by dimakuv** [comment]
## Description of current memory allocators

There are two memory allocators in Gramine: MEMMGR and SLAB.

Both allocators rely on the following shared logic:
- `system_malloc()` and `system_free()` are macros that are defined inside LibOS and in PAL
   - these macros/functions are "back-end" allocations of page-sized contiguous memory regions; i.e. these are *actual host memory allocations*
   - these macros/functions are used to dynamically grow (enlarge) and shrink (not really used!) the slabs/caches in MEMMGR and SLAB
   - defined in LibOS like this:
      - generally: https://github.com/gramineproject/gramine/blob/e740728548ef52615cffdb64f573a998abdfa61f/libos/src/libos_malloc.c#L34
      - special case of VMAs: https://github.com/gramineproject/gramine/blob/e740728548ef52615cffdb64f573a998abdfa61f/libos/src/bookkeep/libos_vma.c#L315
   - defined in PAL like this: https://github.com/gramineproject/gramine/blob/e740728548ef52615cffdb64f573a998abdfa61f/pal/src/slab.c#L28

- `SYSTEM_LOCK()` and `SYSTEM_UNLOCK()` are macros that are defined inside LibOS and in PAL
   - protect the specific MEMMGR "memory managers", each MEMMGR manager object has its own lock; this allows more parallelism as each LibOS subsystem that uses MEMMGR introduces its own lock
   - defined in LibOS like this: 
      - for SLAB: https://github.com/gramineproject/gramine/blob/e740728548ef52615cffdb64f573a998abdfa61f/libos/src/libos_malloc.c#L20-L24
      - for MEMMGR, each LibOS subsystem has its own lock, e.g. for FS operations: https://github.com/gramineproject/gramine/blob/e740728548ef52615cffdb64f573a998abdfa61f/libos/src/fs/libos_dcache.c#L19-L23
   - defined in PAL like this (only SLAB): https://github.com/gramineproject/gramine/blob/e740728548ef52615cffdb64f573a998abdfa61f/pal/src/slab.c#L15-L19

### MEMMGR fixed-size allocator

Used to allocate specific objects in specific subsystems. Currently used only in LibOS.

**STILL WIP***

### SLAB variable-size allocator

Generic backend for malloc and free in all other subsystems. Used both in LibOS and in PAL.

**STILL WIP***
