### ISSUE TITLE
Release 1.6.2 TODO

### ISSUE THREAD

**Issue by woju** [gramineproject/gramine#1807]
- [x] create release PR (@woju) (#1808)
- [x] draft release notes (@mkow or @dimakuv)
- [x] ~~draft blogpost~~
- [x] draft #community announcement (@woju)
- [x] update installation instructions (if a distro was released since last release) (@woju)

iterate (update version, build and upload unstable packages)

final stretch:
- [x] get QA signoff (@woju or @mkow)
- [x] approve PR (@dimakuv and @mkow )
- [x] update version to final and push commits (@woju)
- [x] build final packages (@woju)
- [x] upload packages to release notes (@woju)
- [x] push tag (@woju)
- [x] switch release notes to pushed tag (@woju)
- [x] merge PR (~~@dimakuv or @mkow~~ @woju)
- [x] publish release notes (~~@dimakuv or @mkow~~ @woju)
- [x] ~~publish blogpost~~
- [x] publish on #community (@woju)
