### ISSUE TITLE
Release 1.7 checklist

### ISSUE THREAD

**Issue by woju** [gramineproject/gramine#1847]
- [x] create release PR (@woju) (#1848)
- [x] draft release notes (@mkow or @dimakuv)
- [x] ~~draft blogpost~~
- [x] draft #community announcement (@woju)
- [x] update installation instructions (if a distro was released since last release) (@woju)

iterate (update version, build and upload unstable packages)

final stretch:
- [x] get QA signoff (@woju)
- [x] approve PR (@dimakuv and @mkow)
- [x] update version to final and push commits (@woju)
- [x] build final packages (@woju)
- [x] upload packages to release notes (@woju)
- [x] push tag (@woju)
- [x] switch release notes to pushed tag (@woju)
- [x] merge PR (@woju)
- [x] publish release notes (@woju)
- [x] ~~publish blogpost~~
- [x] publish on #community (@woju)

**Comment by dimakuv** [comment]
I drafted the release notes.
