### ISSUE TITLE
Release 1.8 checklist

### ISSUE THREAD

**Issue by woju** [gramineproject/gramine#2042]
- [x] create release PRs (@woju)
    - gramine: #2022
    - ~gramine-scaffolding:~ (not changed, not releasing)
    - ~contrib:~ (not changed, not releasing) 
- [ ] draft release notes (@woju)
- [x] ~draft blogpost~
- [ ] draft #community announcement (@woju)
- [x] update installation instructions (if a distro was released since last release) (@woju) #1993 

iterate (update version, build and upload unstable packages)

final stretch:
- [ ] get QA signoff (@woju)
- [ ] approve PRs (@dimakuv @mkow)
- [ ] update version to final and push commits (@woju)
- [ ] build final packages (@woju)
- [ ] upload packages to release notes (@woju)
- [ ] push tag (@woju)
- [ ] switch release notes to pushed tag (@woju)
- [ ] merge PR (@woju)
- [ ] publish packages (@woju)
- [ ] publish docker image (@<owner>)
- [ ] publish release notes (@woju)
- [x] ~publish blogpost~
- [ ] publish on #community (@woju)
