### ISSUE TITLE
Security mitigations and hardening

### ISSUE THREAD

**Issue by mkow** [gramineproject/gramine#54]
### Mitigations/sanitizations
- [x] We need better sanitization of OCALL arguments. Current version most likely is not dangerous, but there's a chance that some apps may be manipulated this way into doing something unexpected. See gramineproject/graphene#1236.

### Bug detection
- [x] Run tests with sanitizers in CI (see gramineproject/gramine#19).
- [ ] Run some linters in CI. Problem: most have high false-positive ratios.
- [ ] Implement `__user`-like specifier to check for TOCTOU bugs during compilation (gramineproject/graphene#635; most relevant for OCALLs).

**Comment by dimakuv** [comment]
I think we can close this issue. @mkow If you think that some parts are still relevant, I suggest to create a new issue then.

**Comment by mkow** [comment]
Most of them were solved or brought to a state where further improvements would yield only small gains, so I'm fine with closing it.
