### ISSUE TITLE
Known issues for production deployment

### ISSUE THREAD

**Issue by mkow** [gramineproject/gramine#7]
This issue lists items that need to be kept in mind as you consider using Graphene in a production deployment scenario.

Issues: (checked means "already fixed on master")
- [ ] **Fix all known security issues**\
More information: gramineproject/graphene#2108.
- [ ] **Documenting possible misuses of Graphene and its limitations**\
Graphene has some limitations (some depends one the backends, e.g. that under SGX you can't get trusted time) and users should be aware of them.
- [x] **Rewriting old, buggy and unstable subsystems:**
	- [x] **Filesystem** (rewrite done, see gramineproject/graphene#1803. There will be more features added in the future, but the core rewrite is done)
	- [x] **Signals** (see gramineproject/graphene#2090)
	- [x] **ELF parsing/loading** (the most important part is done, only LibOS loader left, see gramineproject/graphene#1435)
	- [x] **Threading** (done in gramineproject/graphene#1949)
	- [x] **IPC and checkpointing** (done, see gramineproject/graphene#2107)
- [x] **Support for upstreamed SGX driver for Linux**\
~Upstreaming is still in progress, we're blocked on this.~ SGX support made its way to Linux 5.11 and Graphene supports it.
- [x] **Removal of Graphene SGX driver** (done in gramineproject/graphene#1997)\
This driver is insecure and dangerous (see its README) and is only a temporary solution. We will drop it once FSGSBASE patches are upstreamed (that's the only functionality currently left in the driver).
- [x] **Logging system + consistent output format**\
Currently all subsystems output logs in totally random fashion. We also need a better way to control log level.
- [x] **Splitting Graphene output from app output, same for error codes** (partially done)\
Currently those are mixed, which makes the output not really useful in production setup.
Update: Graphene logs can now be redirected to a separate file in the manifest. App stdout and stderr are currently printed to the same host fd and the error codes are still "ANDed", but that's is probably not a blocker for production deployments.
- [x] **Protected filesystem**\
First version almost done, see gramineproject/graphene#1325. Required for most production use-cases.
- [x] **Protected argv and env**\
Using argv and environment from the untrusted world may easily lead to TEE compromise. See gramineproject/graphene#508.

**Comment by dimakuv** [comment]
@mkow Do we still want to keep this meta-issue open? There is one item left ("Documenting possible misuses of Graphene and its limitations"), and we don't have immediate plans to write a document like this.

@pwmarcz Could you mark your todo item ("rewrite db_rtld in PAL") as solved, after I submitted my PRs on this?

**Comment by pwmarcz** [comment]
Done.

**Comment by mkow** [comment]
@dimakuv: I'd keep it and in the meantime try to write up at least a short "secure deployment guidelines" doc, with all the dangers we are aware of clearly listed.

**Comment by dimakuv** [comment]
Looks like the only thing left is this:  **Documenting possible misuses of Graphene and its limitations**

@mkow Can we consider https://github.com/gramineproject/gramine/pull/1194 as fixing it? If yes, then I can add "Fixes 7" to my PR, and we'll automatically close this issue.

**Comment by mkow** [comment]
Nope, this one is completely different? Your document is describing current Gramine state and limitations from the compatibility point of view, the one here is about security. Although reading it now I think I should have describe it better...
Anyways, I have a draft prepared already, need to finish it up finally.
