### ISSUE TITLE
Leftovers from signal rework

### ISSUE THREAD

**Issue by boryspoplawski** [gramineproject/gramine#84]
## Description of the problem
To finish signal rework (#2090) following TOODs/issues need to be fixed:
- [ ] initial, Pal allocated stack can be reused as LibOS syscall emulation stack,
- [ ] revisit locking around each thread->field - since there is no nested syscall calling, some might be accessed lockless,
- [ ] support SA_AUTODISARM,
- [ ] revisit PAL-Linux-SGX signal handling, also tracked in gramineproject/graphene#2533
- [x] ~remove `LEAVE_PAL_CALL` and friends,~ gramineproject/graphene#2149
- [x] ~remove DkRaiseFailure (but this needs a PAL API rework - to return errors directly).~ gramineproject/graphene#2182
